### ISSUE TITLE
Parameters's versioning TO-DO

### ISSUE THREAD

**Issue by brunoolivieri** [ArduPilot/ardupilot_wiki#2449]
Please write here any issue regarding parameters versioning:

- [x] Multiversioning is not loading the parameters toc tree in left panel; PR #2493
- [x] Caching of built previous versions is not working as planned. So, the building time on server takes longer than planned; 
- [x] List box of previous verisons is not preseting the ordered JSON.

**Comment by brunoolivieri** [comment]
done

**Comment by Hwurzburg** [comment]
and well done...thanks!
