### ISSUE TITLE
Autorotation: Setup Page Important Info Tracker

### ISSUE THREAD

**Issue by Gone4Dirt** [ArduPilot/ardupilot_wiki#5739]
This is a tracker to capture important information that we need to convey to users, ensuring that it gets captured in the Wiki:

- [ ] Downward facing LiDaR filter must be 0 Hz cut off.
- [ ] Recommendations for reliable LiDaR units known to work well for auto's?
- [ ] Vehicle mass estimation checks in glide phase.
